__author__ = 'zeroonehacker'

from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import datetime
data ={"name":"dummy","roll":"dummy","air":"dummy","ptype":"dummy","choice1":"dummy","choice2":"dummy","spi1":"dummy","choice3":"dummy","choice4":"dummy","choice5":"dummy"}
def pdf_gen(pdf_file,data=data):
    now = datetime.datetime.now()
    #pdf_file = canvas.Canvas("Branch_Change_Form.pdf")
    pdf_file.rect(0.4*inch,10.7*inch,7.37*inch,0.3*inch)
    pdf_file.setFont('Times-Bold',12)
    pdf_file.drawCentredString(4.1*inch,10.78*inch,"APPLICATION FORM FOR CHANGE OF BRANCH FOR SESSION 2014-15")
    pdf_file.rect(6.2*inch,10.3*inch,1.5*inch,0.2*inch)
    pdf_file.setFont('Courier',12)
    pdf_file.drawString(6.23*inch,10.32*inch,"Date:"+str(now.year)+"-"+str(now.month)+"-"+str(now.day))
    text_object = pdf_file.beginText(0.4*inch,9.3*inch)
    text_object.setFont('Times-Bold',10)
    text_object.textLine("The Chairman SUGC")
    text_object.textLine("Indian Institute Of Technology")
    text_object.textLine("(Banasras Hindu University)")
    pdf_file.drawText(text_object)
    text_object4 = pdf_file.beginText(3.4*inch,8.6*inch)
    text_object4.setFont('Times-Bold',10)
    text_object4.textLine("")
    text_object4.textLine("")
    text_object4.textLine("")
    text_object4.textLine("")
    text_object4.textLine("")
    text_object4.textLine(data["name"])
    text_object4.textLine(data["air"])
    text_object4.textLine(data["roll"])
    text_object4.textLine(data["ptype"])
    text_object4.textLine("")
    text_object4.textLine(data["choice1"])
    text_object4.textLine(data["choice2"])
    text_object4.textLine(data["choice3"])
    text_object4.textLine(data["choice4"])
    text_object4.textLine(data["choice5"])
    pdf_file.drawText(text_object4)
    text_object1 = pdf_file.beginText(0.4*inch,8.6*inch)
    text_object1.setFont('Courier',10)
    text_object1.textLine("Dear Sir,")
    text_object1.textLine("In Accordance with the notification number IIT(BHU)/ACD/2014-15/ .. .. /L dated")
    text_object1.textLine("11.07.2014 , hereby submit my application for change of branch. The requisite Details are ")
    text_object1.textLine("given below:")
    text_object1.textLine(" ")
    text_object1.textLine("1. NAME :" )
    text_object1.textLine("2. ALL INDIA RANK(JEE ADVANCED :")
    text_object1.textLine("3. ROLL NUMBER :" )
    text_object1.textLine("4. ACADEMIC PROGRAMME : " )
    text_object1.textLine("5. Change of Discipline desired now in order of preference : ")
    text_object1.textLine("      FIRST Preference : " )
    text_object1.textLine("      SECOND Preference : " )
    text_object1.textLine("      THIRD Preference : " )
    text_object1.textLine("      FOURTH Preference : " )
    text_object1.textLine("      FIFTH Preference : " )
    text_object1.textLine("6. SPI/CPI OF UGD/IDD/IMD Part I :   ")
    text_object1.setFont('Times-Bold',10)
    pdf_file.drawText(text_object1)
    pdf_file.drawString(2.0*inch,4.5*inch,"Note:")
    pdf_file.setFont('Courier',8)
    pdf_file.drawString(2.4*inch,4.5*inch,"Once a Discipline change is made there will be no further change.")
    pdf_file.drawString(5.9*inch,4.86*inch,"Full Signature of Student")
    pdf_file.setDash([1,1,3,3,1,4,4,1],0)
    pdf_file.line(5.8*inch,5.0*inch,7.6 *inch,5.0*inch)
    pdf_file.setDash([])
    pdf_file.line(0.4*inch,4.4*inch,7.8*inch,4.4*inch)
    pdf_file.setFont('Times-Bold',14)
    pdf_file.drawString(3.5*inch,4.1*inch,"RECEIPT")
    pdf_file.line(3.5*inch,4.0*inch,4.35*inch,4.0*inch)
    text_object2 = pdf_file.beginText(0.4*inch,3.6*inch)
    text_object2.setFont('Courier',10)
    text_object2.textLine("Received filled in Discipline change application form from Mr./Ms.")
    text_object2.textLine("Roll No. : ")
    pdf_file.drawText(text_object2)
    pdf_file.setFont("Times-Bold",10)
    pdf_file.drawString(6.0*inch,3.6*inch,data["name"])
    pdf_file.drawString(1.5*inch,3.45*inch,data["roll"])
    pdf_file.setFont('Courier',10)
    text_object3 = pdf_file.beginText(5.6*inch,6.05*inch)
    text_object3.setFont('Courier',10)
    text_object3.textLine(" SPI I Semester : " )
    pdf_file.setFont('Times-Bold',10)
    pdf_file.drawString(7.2*inch,6.05*inch,str(data["spi1"]))
    pdf_file.setFont('Courier',10)
    text_object3.textLine("*SPI II Semester : ")
    text_object3.textLine("*CPI PART - I : ")
    text_object3.textLine("*PI Part - I")
    pdf_file.drawText(text_object3)
    pdf_file.drawString(0.4*inch,2.8*inch,"Signature of Receiver")
    pdf_file.drawString(0.4*inch,2.5*inch,"Academic Section, IIT(BHU)")
    pdf_file.drawString(6.2*inch,2.8*inch,"Date : ")
    pdf_file.line(0.4*inch,2.3*inch,7.8*inch,2.3*inch)
    pdf_file.setFont('Times-Bold',10)
    pdf_file.drawString(0.4*inch,2.15*inch,"Note:")
    pdf_file.setFont('Courier',8)
    pdf_file.drawString(1.4*inch,5.5*inch,"*to be filled by the office")
    pdf_file.drawString(0.8*inch,2.15*inch,"Once a Discipline change is made there will be no further change.")
    return pdf_file
    pdf_file.showPage()
    pdf_file.save()
if __name__=='__main__':
    pdf_file = canvas.Canvas('Branch_Change_Form.pdf')
    pdf_gen(pdf_file)
