__author__ = 'zeroonehacker'

from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import datetime
import os.path


data ={"name":"dummy","roll":"dummy","air":"dummy","email":"dummy","ptype":"dummy","branch":"dummy","choice1":"dummy","choice2":"dummy","spi1":"","choice3":"d","choice4":"d","choice5":"d"}

mapping = {"year4":"4 year","year5":"5 year","null":"","cer-ugd":"UGD in Ceramic Engineering","che-ugd":"UGD in Chemical Engineering","civ-ugd":"UGD in Civil Engineering","cse-ugd":"UGD in Computer Science and Engineering","eee-ugd":"UGD in Electrical Engineering","ece-ugd":"UGD in Electronics Engineering","mec-ugd":"UGD in Mechanical Engineering","met-ugd":"UGD in Metallurgical Engineering","min-ugd":"UGD in Mining Engineering","apc-imd":"IMD in Industrial Chemistry","mat-imd":"IMD in Mathematics and Computing","app-imd":"IMD in Engineering Physics","cer-idd":"IDD in Ceramic Engineering","civ-idd":"IDD in Civil Engineering","cse-idd":"IDD in Computer Science and Engineering","eee-idd":"IDD in Electrical Engineering","mec-idd":"IDD in Mechanical Engineering","met-idd":"IDD in Metallurgical Engineering","min-idd":"IDD in Mining Engineering","bce-idd":"IDD in Biochemical Engineering","bme-idd":"IDD with B. Tech. in Bio-Engineering  - M. Tech. in Biomedical Technology","mst-idd":"IDD in Materials Science and Technology","dummy":"","pha-idd":"IDD in Pharmacy","pha-ugd":"UGD in Pharmacy"}
def pdf_gen(pdf_file,data=data):
    now = datetime.datetime.now()
    #pdf_file = canvas.Canvas("Branch_Change_Form.pdf")
    pdf_file.rect(0.4*inch,9.7*inch,7.37*inch,0.3*inch)
    pdf_file.setFont('Times-Bold',12)
    pdf_file.drawCentredString(4.1*inch,9.78*inch,"APPLICATION FORM FOR CHANGE OF DISCIPLINE FOR SESSION 2015-16")
    pdf_file.rect(6.2*inch,9.28*inch,1.5*inch,0.2*inch)
    pdf_file.setFont('Courier',12)
    pdf_file.drawString(6.23*inch,9.32*inch,"Date:"+str(now.year)+"-"+str(now.month)+"-"+str(now.day))
    text_object4 = pdf_file.beginText(3.4*inch,8.6*inch)
    text_object4.setFont('Times-Bold',10)
    text_object4.textLine(data["name"])
    text_object4.textLine(data["air"])
    text_object4.textLine(data["roll"])
    text_object4.textLine(mapping[data["ptype"]] +"    "+mapping[data["branch"]])
    text_object4.textLine(data["email"])
    text_object4.textLine("")
    text_object4.textLine("")
    text_object4.textLine(mapping[data["choice1"]])
    text_object4.textLine(mapping[data["choice2"]])
    text_object4.textLine(mapping[data["choice3"]])
    text_object4.textLine(mapping[data["choice4"]])
    text_object4.textLine(mapping[data["choice5"]])
    pdf_file.drawText(text_object4)
    text_object1 = pdf_file.beginText(0.4*inch,8.6*inch)
    text_object1.setFont('Courier',10)
    text_object1.textLine("1. NAME :" )
    text_object1.textLine("2. ALL INDIA RANK(JEE ADVANCED :")
    text_object1.textLine("3. ROLL NUMBER :" )
    text_object1.textLine("4. ACADEMIC PROGRAMME : " )
    text_object1.textLine("5. Email : ")
    text_object1.textLine("6. Change of Discipline desired now in order of preference : ")
    text_object1.textLine("")
    text_object1.textLine("      FIRST Preference : " )
    text_object1.textLine("      SECOND Preference : " )
    text_object1.textLine("      THIRD Preference : " )
    text_object1.textLine("      FOURTH Preference : " )
    text_object1.textLine("      FIFTH Preference : " )
    text_object1.textLine("")
    text_object1.textLine("7. SPI/CPI OF UGD/IDD/IMD Part I :   ")
    text_object1.setFont('Times-Bold',10)
    pdf_file.drawText(text_object1)
    pdf_file.drawString(2.0*inch,4.5*inch,"Note:")
    pdf_file.setFont('Courier',8)
    pdf_file.drawString(2.4*inch,4.5*inch,"Once a change of discipline is made there will be no further change.")
    pdf_file.drawString(5.9*inch,4.86*inch,"Full Signature of Student")
    pdf_file.setDash([1,1,3,3,1,4,4,1],0)
    pdf_file.line(5.8*inch,5.0*inch,7.6 *inch,5.0*inch)
    pdf_file.setDash([])
    pdf_file.line(0.4*inch,4.4*inch,7.8*inch,4.4*inch)
    pdf_file.setFont('Times-Bold',14)
    pdf_file.setFont('Times-Bold',14)
    pdf_file.drawString(3.5*inch,4.1*inch,"RECEIPT")
    pdf_file.line(3.5*inch,4.0*inch,4.35*inch,4.0*inch)
    text_object2 = pdf_file.beginText(0.4*inch,3.6*inch)
    text_object2.setFont('Courier',10)
    text_object2.textLine("Received filled in Discipline change application form from Mr./Ms.")
    text_object2.textLine("Roll No. : ")
    pdf_file.drawText(text_object2)
    pdf_file.setFont("Times-Bold",10)
    pdf_file.drawString(6.0*inch,3.6*inch,data["name"])
    pdf_file.drawString(1.5*inch,3.45*inch,data["roll"])
    pdf_file.setFont('Courier',10)
    text_object3 = pdf_file.beginText(5.6*inch,6.05*inch)
    text_object3.setFont('Courier',10)
    text_object3.textLine(" SPI I Semester : " )
    pdf_file.setFont('Times-Bold',10)
    pdf_file.drawString(7.2*inch,6.05*inch,str(data["spi1"]))
    pdf_file.setFont('Courier',10)
    text_object3.textLine("*SPI II Semester : ")
    text_object3.textLine("*CPI PART - I : ")
    text_object3.textLine("*PI Part - I")
    pdf_file.drawText(text_object3)
    pdf_file.drawString(0.4*inch,2.8*inch,"Signature of Receiver")
    pdf_file.drawString(0.4*inch,2.5*inch,"Academic Section, IIT(BHU)")
    pdf_file.drawString(6.2*inch,2.8*inch,"Date : ")
    pdf_file.line(0.4*inch,2.3*inch,7.8*inch,2.3*inch)
    pdf_file.setFont('Times-Bold',10)
    pdf_file.drawString(0.4*inch,2.15*inch,"Note:")
    pdf_file.setFont('Courier',8)
    pdf_file.drawString(1.4*inch,5.5*inch,"*to be filled by the office")
    logo = os.path.join(os.path.dirname(os.path.abspath(__file__)),'logo.jpg')
    emblem = os.path.join(os.path.dirname(os.path.abspath(__file__)),'emblem.jpg')
    pdf_file.drawString(0.8*inch,2.15*inch,"Once a change of discipline is made there will be no further change.")
    pdf_file.drawImage(logo,0.6*inch,10.26*inch,width=1.2*inch,height=1.2*inch)
    pdf_file.drawImage(emblem,1.8*inch,10.26*inch,width=6.0*inch,height=1.2*inch)
    return pdf_file
    pdf_file.showPage()
    pdf_file.save()
if __name__=='__main__':
    pdf_file = canvas.Canvas('Discipline_Change_Form.pdf')
    pdf_gen(pdf_file)
